project:
  type: website
  title: "Intro to Python for Omics Data Analysis"
  output-dir: ../docs


website:
  title: "Intro to Python for Omics Data Analysis"
  announcement: 
    content: "**Notice** This website is a work in progress! Some tutorials may be incomplete or missing images."
    position: below-navbar
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Basics
        icon: file-code-fill
        menu:
          - gettingstarted.qmd
      - text: Advanced
        icon: file-code
        menu:
          - geojson_annot.qmd
          - cellpose_segmentation.qmd
      - text: Extras
        icon: backpack-fill
        menu:
          - refdump.qmd

    
    right: 
      - icon: github
        href: https://github.com/daniv-20/IntroToPythonForOmicsDataAnalysis

  sidebar:
    style: "docked"
    search: true
    contents: 
      - index.qmd
      
  page-navigation: true


format:
  html:
    theme:
      - cosmo
    dark:
      - darkly
    toc: true
    code-copy: true
  
date: today
date-format: iso



